name: Deploy from Private Repo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Clean public repo (except .git and workflow)
        run: |
          find . -mindepth 1 \
            ! -regex '^\.\/\.git\(\/.*\)?' \
            ! -regex '^\.\/\.github\(\/.*\)?' \
            -exec rm -rf {} +

      - name: Clone private repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/SpiralDJ/test-site-src.git private-src
          echo "Private repo contents:"
          ls -la private-src

      - name: Copy deployable files
        run: |
          cp -r private-src/. .
          rm -rf private-src

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Auto Deployer"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy from private repo" || echo "No changes to commit"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

